# Generated by Django 5.2.14 on 2026-05-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='instigram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='x',
            new_name='twitter',
        ),
    ]
