# Generated by Django 5.2.14 on 2026-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='prices',
            new_name='price',
        ),
        migrations.AddField(
            model_name='food',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
