# Generated by Django 5.2.14 on 2026-05-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_prices_food_price_food_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='general', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(default='general', unique=True),
            preserve_default=False,
        ),
    ]
