# Generated by Django 5.2.14 on 2026-05-30 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delivery_type', models.CharField(choices=[('foot', 'On Foot'), ('restaurant_vehicle', 'Restaurant Vehicle'), ('external_rider', 'External Rider')], max_length=30)),
                ('external_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_time', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('takeout', 'Takeout'), ('delivery', 'Delivery')], default='takeout', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('walking', 'Walking'), ('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
