# Generated by Django 5.2.14 on 2026-06-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('takeout', 'Takeout'), ('delivery', 'Delivery')], default='takeout', max_length=20),
        ),
    ]
