# Generated by Django 5.2.14 on 2026-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_refundrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
