# Generated by Django 5.2.14 on 2026-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_payment_mpesa_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
