# Generated by Django 5.2.14 on 2026-06-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_paymentattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='mercahant_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='mpesa_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
