# Generated by Django 5.2.14 on 2026-06-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_paymentattempt_mercahant_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='food_name',
            field=models.CharField(default="Unknown Food", max_length=200),
            preserve_default=False,
        ),
    ]
