# Generated by Django 5.2.14 on 2026-06-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryzone',
            old_name='external_delivery_fee',
            new_name='delivery_fee',
        ),
    ]
